local L = LibStub("AceLocale-3.0"):NewLocale("EPGP", "enUS", true)
if not L then return end

L["%d or %d"] = true
L["%+d EP (%s) to %s"] = true
L["%+d GP (%s) to %s"] = true
L["%s: %+d EP (%s) to %s"] = true
L["%s: %+d GP (%s) to %s"] = true
L["Alts"] = true
L["Automatic loot tracking threshold"] = true
L["Award EP"] = true
L["Base GP should be a positive number"] = true
L["Credit GP to %s"] = true
L["Credit GP"] = true
L["Custom announce channel name"] = true
L["Decay EP and GP by %d%%?"] = true
L["Decay Percent should be a number between 0 and 100"] = true
L["Decay of EP/GP by %d%%"] = true
L["Decay"] = true
L["EP Reason"] = true
L["EPGP is an in game, relational loot distribution system"] = true
L["EPGP is using Officer Notes for data storage. Do you really want to edit the Officer Note by hand?"] = true
L["EP/GP are reset"] = true
L["Enable GP on tooltips"] = true
L["Enable a proposed GP value of armor on tooltips. Quest items or tokens that can be traded with armor will also have a proposed GP value."] = true
L["Enable announce of actions"] = true
L["Enable announcement of all EPGP actions to the specified medium."] = true
L["Enable automatic loot tracking by means of a popup to assign GP to the toon that received loot. This option only has effect if you are in a raid and you are either the Raid Leader or the Master Looter."] = true
L["Enable automatic loot tracking"] = true
L["GP Reason"] = true
L["GP: %d [ItemLevel=%d]"] = true
L["GP: %d or %d [ItemLevel=%d]"] = true
L["Hint: You can open these options by typing /epgp config"] = true
L["Mass EP Award"] = true
L["Min EP should be a positive number"] = true
L["Next award in "] = true
L["Other"] = true
L["Personal Action Log"] = true
L["Recurring"] = true
L["Reset EPGP"] = true
L["Reset all main toons' EP and GP to 0?"] = true
L["Resets EP and GP of all members of the guild. This will set all main toons' EP and GP to 0. Use with care!"] = true
L["Sets automatic loot tracking threshold, to disable the popup on loot below this threshold quality."] = true
L["Set the announce medium"] = true
L["Sets the announce medium EPGP will use to announce EPGP actions."] = true
L["Sets the custom announce channel name used to announce EPGP actions."] = true
L["Show everyone"] = true
L["Start recurring award (%s) %d EP/%s"] = true
L["Stop recurring award"] = true
L["This menu displays items recently seen by your client"] = true
L["Undo"] = true
L["Value"] = true
