local L = LibStub("AceLocale-3.0"):NewLocale("EPGP", "enUS", true)
if not L then return end

L["%d or %d"] = true
L["%+d EP (%s) to %s"] = true
L["%+d GP (%s) to %s"] = true
L["Decay=%s%% BaseGP=%s MinEP=%s Extras=%s%%"] = true
L["%s is added to the award list"] = true
L["%s is already in the award list"] = true
L["%s is dead. Award EP?"] = true
L["%s is not eligible for EP awards"] = true
L["%s is now removed from the award list"] = true
L["%s: %+d EP (%s) to %s"] = true
L["%s: %+d GP (%s) to %s"] = true
L["Alts"] = true
L["Automatic boss kill tracking"] = true
L["Automatic loot tracking threshold"] = true
L["Award EP"] = true
L["Base GP should be a positive number"] = true
L["Credit GP to %s"] = true
L["Credit GP"] = true
L["Custom announce channel name"] = true
L["Decay EP and GP by %d%%?"] = true
L["Decay Percent should be a number between 0 and 100"] = true
L["Decay of EP/GP by %d%%"] = true
L["Decay"] = true
L["EP Reason"] = true
L["EPGP is an in game, relational loot distribution system"] = true
L["EPGP is using Officer Notes for data storage. Do you really want to edit the Officer Note by hand?"] = true
L["EP/GP are reset"] = true
L["Enable GP on tooltips"] = true
L["Enable a proposed GP value of armor on tooltips. Quest items or tokens that can be traded with armor will also have a proposed GP value."] = true
L["Enable announce of actions"] = true
L["Enable announcement of all EPGP actions to the specified medium."] = true
L["Enable automatic boss tracking by means of a popup to mass award EP to the raid and standby when a boss is killed."] = true
L["Enable automatic loot tracking by means of a popup to assign GP to the toon that received loot. This option only has effect if you are in a raid and you are either the Raid Leader or the Master Looter."] = true
L["Enable automatic loot tracking"] = true
L["Enable standby whispers in raid"] = true
L["Enable automatic handling of the standby list through whispers when in raid. When this option is selected the standby list is cleared after each reward"] = true
L["Export"] = true
L["Extras Percent should be a number between 0 and 100"] = true
L["GP Reason"] = true
L["GP: %d [ItemLevel=%d]"] = true
L["GP: %d or %d [ItemLevel=%d]"] = true
L["Hint: You can open these options by typing /epgp config"] = true
L["If you want to be on the award list but you are not in the raid, you need to whisper me: 'epgp standby' or 'epgp standby <name>' where <name> is the toon that should receive awards"] = true
L["Ignoring non-existent member %s"] = true
L["Import"] = true
L["Importing data snapshot taken at: %s"] = true
L["Invalid officer note [%s] for %s (ignored)"] = true
L["List errors"] = true
L["Lists errors during officer note parsing to the default chat frame. Examples are members with an invalid officer note."] = true
L["Mass EP Award"] = true
L["Min EP should be a positive number"] = true
L["Next award in "] = true
L["Other"] = true
L["Personal Action Log"] = true
L["Recurring"] = true
L["Redo"] = true
L["Reset EPGP"] = true
L["Reset all main toons' EP and GP to 0?"] = true
L["Resets EP and GP of all members of the guild. This will set all main toons' EP and GP to 0. Use with care!"] = true
L["Rollback EPGP"] = true
L["Rollback to snapshot taken on %s?"] = true
L["Rollbacks to the latest snapshot of EPGP taken at logout"] = true
L["Sets automatic loot tracking threshold, to disable the popup on loot below this threshold quality."] = true
L["Set the announce medium"] = true
L["Sets the announce medium EPGP will use to announce EPGP actions."] = true
L["Sets the custom announce channel name used to announce EPGP actions."] = true
L["Show everyone"] = true
L["Start recurring award (%s) %d EP/%s"] = true
L["Stop recurring award"] = true
L["The imported data is invalid"] = true
L["To export the current standings, copy the text below and post it to the webapp: http://epgpweb.appspot.com"] = true
L["To restore to an earlier version of the standings, copy and paste the text from the webapp: http: http://epgpweb.appspot.com here"] = true
L["Undo"] = true
L["Using DBM for boss kill tracking"] = true
L["Value"] = true
