local L = LibStub("AceLocale-3.0"):NewLocale("EPGP", "koKR", true)
if not L then return end

L["Alts"] = "Alts" -- Requires localization
L["Automatic boss kill tracking"] = "자동 보스 처치 추적"
L["Automatic loot tracking threshold"] = "자동 루팅 추적 등급" -- Needs review
L["Award EP"] = "보상 EP"
L["Base GP should be a positive number"] = "기본 GP는 반드시 0보다 커야합니다."
L["Credit GP"] = "Credit GP" -- Requires localization
L["Credit GP to %s"] = "Credit GP to %s" -- Requires localization
L["Custom announce channel name"] = "Custom announce channel name" -- Requires localization
L["Decay"] = "삭감"
L["Decay EP and GP by %d%%?"] = "EP 와 GP 를 %d%% 만큼 삭감합니까?"
L["Decay of EP/GP by %d%%"] = "EP/GP를 %d%%만큼 삭감"
L["Decay Percent should be a number between 0 and 100"] = "삭감 비율은 반드시 0과 100 사이의 값이어야 합니다."
L["Decay=%s%% BaseGP=%s MinEP=%s Extras=%s%%"] = "Decay=%s%% BaseGP=%s MinEP=%s Extras=%s%%" -- Requires localization
L["%+d EP (%s) to %s"] = "%+d EP (%s) to %s" -- Requires localization
L["%+d GP (%s) to %s"] = "%+d GP (%s) to %s" -- Requires localization
L["%d or %d"] = "%d 또는 %d"
L["Enable announcement of all EPGP actions to the specified medium."] = "모든 EPGP 동작을 특정 채널에 알립니다."
L["Enable announce of actions"] = "동작 알림"
L["Enable a proposed GP value of armor on tooltips. Quest items or tokens that can be traded with armor will also have a proposed GP value."] = "장비 툴팁에 제시된 GP 값을 표시합니다. 장비로 교환 가능한 퀘스트 아이템이나 토큰도 제시된 GP 값을 가집니다." -- Needs review
L["Enable automatic boss tracking by means of a popup to mass award EP to the raid and standby when a boss is killed."] = "자동 보스 추적은 보스를 죽였을 때 공격대와 대기자에게 단체 EP 보상을 띄우게 합니다" -- Needs review
L["Enable automatic handling of the standby list through whispers when in raid. When this option is selected the standby list is cleared after each reward"] = "Enable automatic handling of the standby list through whispers when in raid. When this option is selected the standby list is cleared after each reward" -- Requires localization
L["Enable automatic loot tracking"] = "자동 루팅 추적"
L["Enable automatic loot tracking by means of a popup to assign GP to the toon that received loot. This option only has effect if you are in a raid and you are either the Raid Leader or the Master Looter."] = "자동 루팅 추적은 케릭터가 전리품을 받았을 때 GP 할당을 띄우게 합니다. 이 옵션은 당신이 공격대장 이거나 전리품 담당자 일때만 작동합니다."
L["Enable GP on tooltips"] = "툴팁에 GP 표시"
L["Enable standby whispers in raid"] = "공격대 대기자 귓속말" -- Needs review
L["EP/GP are reset"] = "EP/GP 가 초기화됩니다"
L["EPGP is an in game, relational loot distribution system"] = "EPGP 는 게임 내, 상관적 루팅 분배 시스템 입니다"
L["EPGP is using Officer Notes for data storage. Do you really want to edit the Officer Note by hand?"] = "EPGP 는 오피서 노트를 기록 장소로 사용합니다. 정말로 오피서 노트를 직접 수정하겠습니까?"
L["EP Reason"] = "EP 근거"
L["Extras Percent should be a number between 0 and 100"] = "Extras Percent should be a number between 0 and 100" -- Requires localization
L["GP: %d [ItemLevel=%d]"] = "GP: %d [아이템레벨=%d]"
L["GP: %d or %d [ItemLevel=%d]"] = "GP: %d 또는 %d [아이템레벨=%d]"
L["GP Reason"] = "GP 근거"
L["Hint: You can open these options by typing /epgp config"] = "힌트: 채팅창에 '/epgp config' 를 입력하여 이 옵션창을 열 수 있습니다."
L["If you want to be on the award list but you are not in the raid, you need to whisper me: 'epgp standby' or 'epgp standby <name>' where <name> is the toon that should receive awards"] = "If you want to be on the award list but you are not in the raid, you need to whisper me: 'epgp standby' or 'epgp standby <name>' where <name> is the toon that should receive awards" -- Requires localization
L["Invalid officer note [%s] for %s (ignored)"] = "Invalid officer note [%s] for %s (ignored)" -- Requires localization
L["List errors"] = "목록 오류"
L["Lists errors during officer note parsing to the default chat frame. Examples are members with an invalid officer note."] = "Lists errors during officer note parsing to the default chat frame. Examples are members with an invalid officer note." -- Requires localization
L["Mass EP Award"] = "단체 EP 보상"
L["Min EP should be a positive number"] = "최소 EP는 반드시 0보다 커야 합니다."
L["Next award in "] = "다음 보상은 "
L["Other"] = "기타"
L["Personal Action Log"] = "개인 동작 기록"
L["Recurring"] = "반복"
L["Redo"] = "다시 실행"
L["Reset all main toons' EP and GP to 0?"] = "모든 케릭터의 EP 와 GP를 0으로 초기화 하겠습니까?"
L["Reset EPGP"] = "EPGP 초기화"
L["Resets EP and GP of all members of the guild. This will set all main toons' EP and GP to 0. Use with care!"] = "모든 멤버의 EP와 GP가 0으로 초기화 되었습니다. 신중히 사용하세요!"
L["Rollback EPGP"] = "EPGP 복원"
L["Rollbacks to the latest snapshot of EPGP taken at logout"] = "Rollbacks to the latest snapshot of EPGP taken at logout" -- Requires localization
L["Rollback to snapshot taken on %s?"] = "%s 의 기록 지점으로 복원하겠습니까?"
L["%s: %+d EP (%s) to %s"] = "%s: %+d EP (%s) to %s" -- Requires localization
L["%s: %+d GP (%s) to %s"] = "%s: %+d GP (%s) to %s" -- Requires localization
L["Sets automatic loot tracking threshold, to disable the popup on loot below this threshold quality."] = "이 등급 이하의 루팅에서 팝업을 취소하려면, 자동 루팅 추적 등급 을 설정하세요." -- Needs review
L["Sets the announce medium EPGP will use to announce EPGP actions."] = "EPGP 알림 채널을 설정하면 EPGP 동작을 채널에 보고하게 됩니다."
L["Sets the custom announce channel name used to announce EPGP actions."] = "EPGP 동작을 알릴 사용자 알림 채널을 설정하세요."
L["Set the announce medium"] = "알림 채널 설정"
L["Show everyone"] = "모두 보이기"
L["%s is added to the award list"] = "%s 가 보상 목록에 추가되었습니다."
L["%s is already in the award list"] = "%s 는 이미 보상 목록에 포함되어 있습니다."
L["%s is dead. Award EP?"] = "%s 가 죽었습니다. EP 를 부여할까요?"
L["%s is not eligible for EP awards"] = "%s is not eligible for EP awards" -- Requires localization
L["%s is now removed from the award list"] = "%s 는 이제 보상 목록에서 제거되었습니다."
L["Start recurring award (%s) %d EP/%s"] = "반복 보상 시작 (%s) %d EP/%s"
L["Stop recurring award"] = "반복 보상 중지"
L["Undo"] = "실행 취소"
L["Using DBM for boss kill tracking"] = "Using DBM for boss kill tracking" -- Requires localization
L["Value"] = "값"
